//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int aid { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string phoneno { get; set; }
        public string email { get; set; }
        public string status { get; set; }
        public int sid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> sp_id { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual ServiceProvider ServiceProvider { get; set; }
        public virtual UserM UserM { get; set; }
    }
}
