//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProvider
    {
        public ServiceProvider()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int spid { get; set; }
        public int u_id { get; set; }
        public string name { get; set; }
        public string location { get; set; }
        public string companyName { get; set; }
        public string address { get; set; }
        public string phoneno { get; set; }
        public string email { get; set; }
        public string faxNo { get; set; }
        public string panNo { get; set; }
        public string adhaarNo { get; set; }
        public string referredBy { get; set; }
        public string customerPan { get; set; }
        public string sp_image { get; set; }
        public string serviceCategory { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual UserM UserM { get; set; }
    }
}
