//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int sid { get; set; }
        public int cid { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string service_image { get; set; }
        public string min_cost { get; set; }
        public Nullable<int> pinCode { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Category Category { get; set; }
    }
}
