//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserM
    {
        public UserM()
        {
            this.Appointments = new HashSet<Appointment>();
            this.ServiceProviders = new HashSet<ServiceProvider>();
            this.UserDetails = new HashSet<UserDetail>();
        }
    
        public int uid { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string role { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<ServiceProvider> ServiceProviders { get; set; }
        public virtual ICollection<UserDetail> UserDetails { get; set; }
    }
}
